version: '3.8'
services:
  service_a:
    build: ./service_a
    ports:
      - "5000:5000"
    environment:
      - OTEL_SERVICE_NAME=voting-frontend
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      # --- НАСТРОЙКИ ОПРОСА ---
      - POLL_TITLE=Cats vs Dogs
      - OPTION_A=Cats
      - OPTION_B=Dogs
    depends_on:
      - jaeger
      - service_b

  service_b:
    build: ./service_b
    environment:
      - OTEL_SERVICE_NAME=voting-backend
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OPTION_A=Cats
      - OPTION_B=Dogs
    depends_on:
      - jaeger
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"