services:
  # фронтенд
  service_a:
    build: ./service_a
    ports:
      - "5000:5000"
    environment:
      - OTEL_SERVICE_NAME=voting-frontend
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    depends_on:
      - jaeger
      - service_b

  # бэкенд
  service_b:
    build: ./service_b
    environment:
      - OTEL_SERVICE_NAME=voting-backend
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    depends_on:
      - jaeger
      - redis

  # БД
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # Мониторинг
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"